data: data/combined_data.csv
processed_data: data/processed_data.csv
class_type: binary # binary or multiclass
debug: False
split:
  test_size: 0.048
  train_data_size: 30000000
  test_data_size: 100000